title:            not-much-io blog
description:      some guys blog
url:              not-much-io.github.io
signoff:          Kristo Koert
disqus_shortname: notmuchiogithubio # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Posts
    url:          /
  - name:         Email
    url:          mailto:kristo.koert@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/not-much-io
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
